name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: |
              '*.ps1'
              LICENSE
            generate_release_notes: true
            fail_on_unmatched_files: true
