name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Zip Files
          run: tar cf ModpackUploader.zip modpack-uploader.ps1 settings.ps1 secrets.ps1 get-game-versions.ps1 LICENSE
          
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            generate_release_notes: true
            fail_on_unmatched_files: true
            token: ${{ secrets.GITHUB_TOKEN }}
            files: ModpackUploader.zip
